version: 2.0
# Necessary for running in machine mode, which is necessary to execute the
# Zeppelin and MetaCoin E2E scripts
step_install_nvm: &step_install_nvm
  run:
    name: "Install nvm for machine"
    command: |
      set +e
      export NVM_DIR="/opt/circleci/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      nvm install v8.15.0
      nvm alias default v8.15.0
      echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
      echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
jobs:
  unit-test:
    docker:
      - image: circleci/node:8.15.0
    steps:
      - checkout
      - run:
          name: Delete any old node_modules
          command: |
            rm -rf node_modules/
      - run:
          name: Install dependencies
          command: |
            yarn
      - run:
          name: Run tests
          command: |
            npm run test-cov
      - run:
          name: Upload coverage
          command: |
            bash <(curl -s https://codecov.io/bash)

  # This works but takes a while....
  e2e-colony:
    docker:
      - image: circleci/node:10.12-stretch
    working_directory: ~/colonyNetwork
    steps:
      - checkout
      - run:
          name: ColonyNetwork E2E
          command: |
            ./scripts/run-colony.sh

  # It would be nice if all this could be a shell script... :/
  e2e-zeppelin:
    docker:
      - image: circleci/node:10.12-stretch
    steps:
      - checkout
      - run: >
          sudo rm -rf node_modules &&
          PR_PATH=$(echo "$CIRCLE_REPOSITORY_URL#$CIRCLE_SHA1" | sudo sed 's/git@github.com:/https:\/\/github.com\//') &&
          echo "PR_PATH >>>>> $PR_PATH" &&
          sudo git clone https://github.com/OpenZeppelin/openzeppelin-solidity.git &&
          cd openzeppelin-solidity &&
          sudo sed -i 's/cat coverage\/lcov.info | npx coveralls/echo "No coveralls"/g' scripts/test.sh &&
          sudo sed -i 's/ganache-cli-coverage/testrpc-sc/g' scripts/test.sh &&
          sudo sed -i 's/--emitFreeLogs true/ /g' scripts/test.sh &&
          sudo yarn &&
          sudo yarn remove solidity-coverage --dev &&
          sudo yarn add "$PR_PATH" --dev &&
          sudo npm run coverage

  # AND...this doesn't work either! Thanks to truffle "obtain" and circle permission denied.
  e2e-metacoin:
    machine: true
    steps:
      - checkout
      - <<: *step_install_nvm
      - run:
          name: MetaCoin E2E
          command: |
            ./scripts/run-metacoin.sh
workflows:
  version: 2
  build:
    jobs:
      #- unit-test
      #- e2e-zeppelin
      - e2e-metacoin
  nightly:
    triggers:
      - schedule:
          cron: "0 1 * * *" # 1am UTC
          filters:
            branches:
              only:
                - master
    jobs:
      - e2e-zeppelin
      #- e2e-colony
